add INTERNAL_BJJ_ETH_ADDR constant
hermeznetwork/hermezjs pull request #163
Opened 2021-05-12 21:16 UTC by mmilenkovic

2021-05-13 10:17 UTC, AlbertoElias submitted a review, later dismissed

2021-05-13 10:28 UTC, krlosMata requested changes

2021-05-13 10:28 UTC, krlosMata commented on src/constants.js
> +const EMPTY_BJJ_ETH_ADDR = 'hez:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
```suggestion
const EMPTY_BJJ_ADDR = 'hez:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
```

2021-05-18 08:50 UTC, elias-garcia approved these changes

2021-05-18 08:58 UTC, krlosMata approved these changes
:smile_cat:

2021-05-18 09:07 UTC, merged