support atomic transactions
hermeznetwork/hermezjs pull request #165
Opened 2021-05-13 08:29 UTC by krlosMata

This PR does the following:
- implements method `buildTxCompressedDataV2`
- implements logic to support atomic transactions
- add tests for `buildTxCompressedDataV2` & atomic transactions

2021-05-13 12:12 UTC, AlbertoElias approved these changes

2021-08-03 11:30 UTC, AlbertoElias requested changes
A few small comments

2021-08-03 11:30 UTC, AlbertoElias commented on src/tx-utils.js
> + * @return {Object} - Contains `transaction` and `encodedTransaction`. `transaction` is the object almost ready to be sent to the Coordinator. `encodedTransaction` is needed to sign the `transaction`
No longer contains encodedTransaction

2021-08-03 11:30 UTC, AlbertoElias commented on tests/helpers/helpers.js
> +    if (j !== generateTxs.length - 1) {
why is this? might be good to add a comment

2021-08-04 09:38 UTC, krlosMata commented on src/atomic-utils.js
> +    (transaction.requestFromAccountIndex !== null && transaction.requestFromAccountIndex !== undefined) ||
oh! thanks for sharing!
Although I think here does not fit perfectly

2021-08-04 14:17 UTC, AlbertoElias approved these changes

2021-08-04 21:56 UTC, merged